### ISSUE TITLE
Application is breaking

### ISSUE THREAD

**Issue by Priyankadmehta** [iliketosneeze/TwitterMoodMap#2]
hello,
  when i try to run directly it breaks before displaying on map 
  fatal error: Array index out of range 
  moreover if i want to use this do i have to change anything from my side like api key or anything 

Thanks
Priyanka

**Comment by jcevans92** [comment]
Let's say you have an array with one object in it:

let arr = ["hello"]
The only valid index into that array is 0. arr[0] is legal. arr[1] is not. The array has 1 element but its index number is 0.

This is true for any array. Every array holds some number of elements. It might be 0 elements, in which case no index is legal. It might be 3 elements, in which case you can refer to the array's elements by index numbers 0, 1, and 2. And so on. That's all. Those are the rules. You cannot use any other index number or you will crash.

So the error message is simply telling you that you are making that mistake. You have an array answerRecord and it has some number of elements - I have no idea how many, and it doesn't matter. Then you are using the expression answerRecord[arrayCount] and the value of arrayCount is outside the bounds I have just explained. That's all you need to know. The error message tells you the bug in your program. Now you can fix it.

**Comment by Priyankadmehta** [comment]
Hello,
 Thanks for explaination. I haven't change anything in code and it's
showing bad access in this function. which is in TMMMainViewController file.

dispatch_async(dispatch_get_main_queue(), { () -> Void in

                let region = MKCoordinateRegion(center: moodTweets[0].
getLocation().coordinate, span: MKCoordinateSpan(latitudeDelta: 0.05,
longitudeDelta: 0.05))

                self.mapView.setRegion(region, animated: true)

            })

        })

i just change url path according to my host name so for backend application
 should i have to run index.js separately or from this app it is
automatically calling an api.




Best
Priyanka Mehta
Software Developer || Grad Student || Computer Science

**Comment by imex94** [comment]
You have to run index.js separately. In index.js you have to change the Twitter API_KEY and SECRET_KEY to your own keys. 

Also make sure you change the url in TMMServerManager to the one you're using.

The crash was caused, because there was probably an error fetching data from the API, and we got back an empty array and in the code it tries to get the first element anyway. It's been fixed since, so now your app shouldn't crash.

**Comment by Priyankadmehta** [comment]
Thank you so much for your guidance. really appreciate that. I will follow
your instruction.

Best
Priyanka Mehta
Software Developer || Grad Student || Computer Science
